// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOmqwJOIjGp6eisRFYLfcFcta8msgJ6A',
    appId: '1:883898126883:web:64b46b09d2187fe7c31796',
    messagingSenderId: '883898126883',
    projectId: 'aetherlabs-2304c',
    authDomain: 'aetherlabs-2304c.firebaseapp.com',
    storageBucket: 'aetherlabs-2304c.firebasestorage.app',
    measurementId: 'G-HQMVGPVW63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGstY0QobNrbf6FbqGAy-u5TmiPqO4xzs',
    appId: '1:883898126883:android:181b72152a0f4023c31796',
    messagingSenderId: '883898126883',
    projectId: 'aetherlabs-2304c',
    storageBucket: 'aetherlabs-2304c.firebasestorage.app',
  );
}
